---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/root/NETDEVOPS/NORNIR/PROJECTS/DEMOS/hosts.yaml"
        group_file: "/root/NETDEVOPS/NORNIR/PROJECTS/DEMOS/groups.yaml"
        defaults_file: "/root/NETDEVOPS/NORNIR/PROJECTS/DEMOS/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100
